version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - .:/portfolio
    environment:
      - DJANGO_SETTINGS_MODULE=portfolio.settings.production
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'

